//! vimyc's env tables against the vocabulary real games actually use.
//!
//! `testdata/env_manifest.json` is generated by `TestDumpEnvManifest` in
//! `vimy-core/rules` from 500 doctrines sampled from 64 real games. These are
//! the only checks available until the doctrine rules are ported: they cannot
//! evaluate anything, but they can say whether the tables would even resolve
//! what real play produces.

use serde::Deserialize;
use vimyc::types::Domain;

#[derive(Debug, Deserialize)]
struct Method {
    #[allow(dead_code)]
    name: String,
    kebab: String,
    // `Option` rather than `#[serde(default)]`: Go marshals a nil slice as
    // `null`, and a default only covers a field that is absent.
    params: Option<Vec<Param>>,
    results: Vec<String>,
    domains: Option<Vec<String>>,
    #[serde(default)]
    used: bool,
    literals: Option<Vec<Vec<String>>>,
    /// The exact keys Go's projection records for this method.
    keys: Option<Vec<String>>,
}

impl Method {
    fn params(&self) -> &[Param] {
        self.params.as_deref().unwrap_or(&[])
    }
    fn domains(&self) -> &[String] {
        self.domains.as_deref().unwrap_or(&[])
    }
    fn literals(&self) -> &[Vec<String>] {
        self.literals.as_deref().unwrap_or(&[])
    }
    fn keys(&self) -> &[String] {
        self.keys.as_deref().unwrap_or(&[])
    }
}

#[derive(Debug, Deserialize)]
struct Param {
    #[allow(dead_code)]
    #[serde(rename = "type")]
    ty: String,
}

fn manifest() -> Vec<Method> {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/testdata/env_manifest.json");
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("{path}: {e}\nregenerate with TestDumpEnvManifest"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("{path}: {e}"))
}

fn used() -> Vec<Method> {
    manifest().into_iter().filter(|m| m.used).collect()
}

/// Every predicate a rule can name is in the table, and nothing is in the table
/// that no rule names.
#[test]
fn predicates_match_the_manifest() {
    let have: std::collections::HashSet<&str> =
        vimyc::env::PREDICATES.iter().map(|s| s.name).collect();
    let want: std::collections::HashSet<String> = used().into_iter().map(|m| m.kebab).collect();

    let missing: Vec<&String> = want.iter().filter(|k| !have.contains(k.as_str())).collect();
    let extra: Vec<&&str> = have.iter().filter(|k| !want.contains(**k)).collect();

    assert!(
        missing.is_empty(),
        "rules name these, env.rs lacks them: {missing:?}"
    );
    assert!(
        extra.is_empty(),
        "env.rs has these, no rule names them: {extra:?}"
    );
}

/// Arity and return type agree with Go's actual method signatures.
#[test]
fn signatures_match_the_manifest() {
    let mut wrong = Vec::new();
    for m in used() {
        let Some(sig) = vimyc::env::predicate(&m.kebab) else {
            continue; // reported by predicates_match_the_manifest
        };
        if sig.params.len() != m.params().len() {
            wrong.push(format!(
                "  {}: Go takes {} argument(s), env.rs says {}",
                m.kebab,
                m.params().len(),
                sig.params.len()
            ));
        }
        let go_ret = &m.results[0];
        let ok = match &sig.ret {
            vimyc::types::Type::Bool => go_ret == "bool",
            vimyc::types::Type::Int => go_ret == "int",
            vimyc::types::Type::Float => go_ret == "float64",
            vimyc::types::Type::Collection => go_ret.starts_with("[]"),
            vimyc::types::Type::Option(_) => go_ret.starts_with('*'),
            _ => false,
        };
        if !ok {
            wrong.push(format!(
                "  {}: Go returns {go_ret}, env.rs says {}",
                m.kebab, sig.ret
            ));
        }
    }
    assert!(
        wrong.is_empty(),
        "signature drift from Go:\n{}",
        wrong.join("\n")
    );
}

/// Every literal a real doctrine passes resolves in the domain the parameter
/// expects.
///
/// This is the check that would have caught `v2-launcher` missing from `ROLES`,
/// and it is measured against 500 doctrines from real games rather than against
/// anything invented here.
#[test]
fn every_literal_real_doctrines_pass_resolves() {
    let domain = |name: &str| match name {
        "queue" => Some(Domain::Queue),
        "role" => Some(Domain::Role),
        "building" => Some(Domain::BuildingType),
        "unit" => Some(Domain::UnitType),
        "squad" => Some(Domain::SquadName),
        "axis" => Some(Domain::Axis),
        "support-power" => Some(Domain::SupportPower),
        _ => None,
    };

    let mut unresolved = Vec::new();
    let mut checked = 0usize;

    for m in used() {
        for (i, lits) in m.literals().iter().enumerate() {
            let d = m.domains().get(i).map(String::as_str).unwrap_or("");
            if d == "buildable" {
                for l in lits {
                    checked += 1;
                    if vimyc::env::member(Domain::BuildingType, l).is_none()
                        && vimyc::env::member(Domain::UnitType, l).is_none()
                    {
                        unresolved.push(format!(
                            "  {}({i}): `{l}` is neither a building nor a unit",
                            m.kebab
                        ));
                    }
                }
                continue;
            }
            let Some(dom) = domain(d) else {
                // A numeric parameter, or one no rule passes a literal to.
                continue;
            };
            for l in lits {
                checked += 1;
                if vimyc::env::member(dom, l).is_none() {
                    unresolved.push(format!(
                        "  {}({i}): `{l}` is not a known {}",
                        m.kebab,
                        dom.name()
                    ));
                }
            }
        }
    }

    assert!(
        checked > 100,
        "expected the real-doctrine vocabulary, checked {checked}"
    );
    assert!(
        unresolved.is_empty(),
        "{} of {checked} literals real games pass do not resolve:\n{}",
        unresolved.len(),
        unresolved.join("\n")
    );
    eprintln!("{checked} literals from real doctrines, all resolve");
}

/// vimyc looks a predicate up under exactly the key Go recorded it under.
///
/// This is the failure the differential kept surfacing and no other test could
/// see: Go wrote `squad-threat-ratio(ground-attack,0.10)` from the literal text
/// in a condition while vimyc parsed the same literal and asked for `…,0.1`. The
/// lookup missed, the zero default came back, and the rule quietly evaluated
/// false. A rule that never fires in a recording would hide it forever.
///
/// Checked directly rather than hoped for, because coverage cannot reach it: 69
/// of 91 rules in a real game only ever evaluated false, and an always-false
/// mistranslation agrees with expr every time.
#[test]
fn lookup_keys_match_what_go_records() {
    let mut wrong = Vec::new();
    let mut checked = 0usize;

    for m in used() {
        // Reconstruct what vimyc would look up: the same argument combinations,
        // rendered the way `eval::key` renders them.
        let lits = m.literals();
        let combos: Vec<Vec<String>> = if lits.iter().all(|l| l.is_empty()) {
            vec![vec![]]
        } else {
            lits.iter().fold(vec![vec![]], |acc, vals| {
                let mut next = Vec::new();
                for base in &acc {
                    for v in vals {
                        let mut c = base.clone();
                        c.push(render(v));
                        next.push(c);
                    }
                }
                next
            })
        };

        for c in &combos {
            let key = if c.is_empty() {
                m.kebab.clone()
            } else {
                format!("{}({})", m.kebab, c.join(","))
            };
            checked += 1;
            if !m.keys().contains(&key) {
                wrong.push(format!(
                    "  {} looks up `{key}`, Go records {:?}",
                    m.kebab,
                    m.keys()
                ));
            }
        }
    }

    assert!(
        checked > 100,
        "expected the real key set, checked {checked}"
    );
    assert!(
        wrong.is_empty(),
        "{} of {checked} lookups would miss and read a zero default:\n{}",
        wrong.len(),
        wrong.join("\n")
    );
    eprintln!("{checked} lookup keys, all match what Go records");
}

/// How vimyc renders an argument into a lookup key.
///
/// Calls the real rendering rather than repeating it — a copy would keep passing
/// while the thing it is meant to guard changed underneath.
fn render(lit: &str) -> String {
    match lit.parse::<f64>() {
        Ok(f) if lit.contains('.') => vimyc::state::render_number(f),
        _ => lit.to_string(),
    }
}
